// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"lybbrio/internal/ent/author"
	"lybbrio/internal/ent/book"
	"lybbrio/internal/ent/predicate"
	"lybbrio/internal/ent/schema/ksuid"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AuthorUpdate is the builder for updating Author entities.
type AuthorUpdate struct {
	config
	hooks    []Hook
	mutation *AuthorMutation
}

// Where appends a list predicates to the AuthorUpdate builder.
func (au *AuthorUpdate) Where(ps ...predicate.Author) *AuthorUpdate {
	au.mutation.Where(ps...)
	return au
}

// SetCalibreID sets the "calibre_id" field.
func (au *AuthorUpdate) SetCalibreID(i int64) *AuthorUpdate {
	au.mutation.ResetCalibreID()
	au.mutation.SetCalibreID(i)
	return au
}

// SetNillableCalibreID sets the "calibre_id" field if the given value is not nil.
func (au *AuthorUpdate) SetNillableCalibreID(i *int64) *AuthorUpdate {
	if i != nil {
		au.SetCalibreID(*i)
	}
	return au
}

// AddCalibreID adds i to the "calibre_id" field.
func (au *AuthorUpdate) AddCalibreID(i int64) *AuthorUpdate {
	au.mutation.AddCalibreID(i)
	return au
}

// SetName sets the "name" field.
func (au *AuthorUpdate) SetName(s string) *AuthorUpdate {
	au.mutation.SetName(s)
	return au
}

// SetNillableName sets the "name" field if the given value is not nil.
func (au *AuthorUpdate) SetNillableName(s *string) *AuthorUpdate {
	if s != nil {
		au.SetName(*s)
	}
	return au
}

// SetSort sets the "sort" field.
func (au *AuthorUpdate) SetSort(s string) *AuthorUpdate {
	au.mutation.SetSort(s)
	return au
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (au *AuthorUpdate) SetNillableSort(s *string) *AuthorUpdate {
	if s != nil {
		au.SetSort(*s)
	}
	return au
}

// SetLink sets the "link" field.
func (au *AuthorUpdate) SetLink(s string) *AuthorUpdate {
	au.mutation.SetLink(s)
	return au
}

// SetNillableLink sets the "link" field if the given value is not nil.
func (au *AuthorUpdate) SetNillableLink(s *string) *AuthorUpdate {
	if s != nil {
		au.SetLink(*s)
	}
	return au
}

// ClearLink clears the value of the "link" field.
func (au *AuthorUpdate) ClearLink() *AuthorUpdate {
	au.mutation.ClearLink()
	return au
}

// AddBookIDs adds the "books" edge to the Book entity by IDs.
func (au *AuthorUpdate) AddBookIDs(ids ...ksuid.ID) *AuthorUpdate {
	au.mutation.AddBookIDs(ids...)
	return au
}

// AddBooks adds the "books" edges to the Book entity.
func (au *AuthorUpdate) AddBooks(b ...*Book) *AuthorUpdate {
	ids := make([]ksuid.ID, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return au.AddBookIDs(ids...)
}

// Mutation returns the AuthorMutation object of the builder.
func (au *AuthorUpdate) Mutation() *AuthorMutation {
	return au.mutation
}

// ClearBooks clears all "books" edges to the Book entity.
func (au *AuthorUpdate) ClearBooks() *AuthorUpdate {
	au.mutation.ClearBooks()
	return au
}

// RemoveBookIDs removes the "books" edge to Book entities by IDs.
func (au *AuthorUpdate) RemoveBookIDs(ids ...ksuid.ID) *AuthorUpdate {
	au.mutation.RemoveBookIDs(ids...)
	return au
}

// RemoveBooks removes "books" edges to Book entities.
func (au *AuthorUpdate) RemoveBooks(b ...*Book) *AuthorUpdate {
	ids := make([]ksuid.ID, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return au.RemoveBookIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (au *AuthorUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, au.sqlSave, au.mutation, au.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (au *AuthorUpdate) SaveX(ctx context.Context) int {
	affected, err := au.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (au *AuthorUpdate) Exec(ctx context.Context) error {
	_, err := au.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (au *AuthorUpdate) ExecX(ctx context.Context) {
	if err := au.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (au *AuthorUpdate) check() error {
	if v, ok := au.mutation.Name(); ok {
		if err := author.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Author.name": %w`, err)}
		}
	}
	return nil
}

func (au *AuthorUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := au.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(author.Table, author.Columns, sqlgraph.NewFieldSpec(author.FieldID, field.TypeString))
	if ps := au.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := au.mutation.CalibreID(); ok {
		_spec.SetField(author.FieldCalibreID, field.TypeInt64, value)
	}
	if value, ok := au.mutation.AddedCalibreID(); ok {
		_spec.AddField(author.FieldCalibreID, field.TypeInt64, value)
	}
	if value, ok := au.mutation.Name(); ok {
		_spec.SetField(author.FieldName, field.TypeString, value)
	}
	if value, ok := au.mutation.Sort(); ok {
		_spec.SetField(author.FieldSort, field.TypeString, value)
	}
	if value, ok := au.mutation.Link(); ok {
		_spec.SetField(author.FieldLink, field.TypeString, value)
	}
	if au.mutation.LinkCleared() {
		_spec.ClearField(author.FieldLink, field.TypeString)
	}
	if au.mutation.BooksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   author.BooksTable,
			Columns: author.BooksPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.RemovedBooksIDs(); len(nodes) > 0 && !au.mutation.BooksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   author.BooksTable,
			Columns: author.BooksPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.BooksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   author.BooksTable,
			Columns: author.BooksPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, au.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{author.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	au.mutation.done = true
	return n, nil
}

// AuthorUpdateOne is the builder for updating a single Author entity.
type AuthorUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuthorMutation
}

// SetCalibreID sets the "calibre_id" field.
func (auo *AuthorUpdateOne) SetCalibreID(i int64) *AuthorUpdateOne {
	auo.mutation.ResetCalibreID()
	auo.mutation.SetCalibreID(i)
	return auo
}

// SetNillableCalibreID sets the "calibre_id" field if the given value is not nil.
func (auo *AuthorUpdateOne) SetNillableCalibreID(i *int64) *AuthorUpdateOne {
	if i != nil {
		auo.SetCalibreID(*i)
	}
	return auo
}

// AddCalibreID adds i to the "calibre_id" field.
func (auo *AuthorUpdateOne) AddCalibreID(i int64) *AuthorUpdateOne {
	auo.mutation.AddCalibreID(i)
	return auo
}

// SetName sets the "name" field.
func (auo *AuthorUpdateOne) SetName(s string) *AuthorUpdateOne {
	auo.mutation.SetName(s)
	return auo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (auo *AuthorUpdateOne) SetNillableName(s *string) *AuthorUpdateOne {
	if s != nil {
		auo.SetName(*s)
	}
	return auo
}

// SetSort sets the "sort" field.
func (auo *AuthorUpdateOne) SetSort(s string) *AuthorUpdateOne {
	auo.mutation.SetSort(s)
	return auo
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (auo *AuthorUpdateOne) SetNillableSort(s *string) *AuthorUpdateOne {
	if s != nil {
		auo.SetSort(*s)
	}
	return auo
}

// SetLink sets the "link" field.
func (auo *AuthorUpdateOne) SetLink(s string) *AuthorUpdateOne {
	auo.mutation.SetLink(s)
	return auo
}

// SetNillableLink sets the "link" field if the given value is not nil.
func (auo *AuthorUpdateOne) SetNillableLink(s *string) *AuthorUpdateOne {
	if s != nil {
		auo.SetLink(*s)
	}
	return auo
}

// ClearLink clears the value of the "link" field.
func (auo *AuthorUpdateOne) ClearLink() *AuthorUpdateOne {
	auo.mutation.ClearLink()
	return auo
}

// AddBookIDs adds the "books" edge to the Book entity by IDs.
func (auo *AuthorUpdateOne) AddBookIDs(ids ...ksuid.ID) *AuthorUpdateOne {
	auo.mutation.AddBookIDs(ids...)
	return auo
}

// AddBooks adds the "books" edges to the Book entity.
func (auo *AuthorUpdateOne) AddBooks(b ...*Book) *AuthorUpdateOne {
	ids := make([]ksuid.ID, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return auo.AddBookIDs(ids...)
}

// Mutation returns the AuthorMutation object of the builder.
func (auo *AuthorUpdateOne) Mutation() *AuthorMutation {
	return auo.mutation
}

// ClearBooks clears all "books" edges to the Book entity.
func (auo *AuthorUpdateOne) ClearBooks() *AuthorUpdateOne {
	auo.mutation.ClearBooks()
	return auo
}

// RemoveBookIDs removes the "books" edge to Book entities by IDs.
func (auo *AuthorUpdateOne) RemoveBookIDs(ids ...ksuid.ID) *AuthorUpdateOne {
	auo.mutation.RemoveBookIDs(ids...)
	return auo
}

// RemoveBooks removes "books" edges to Book entities.
func (auo *AuthorUpdateOne) RemoveBooks(b ...*Book) *AuthorUpdateOne {
	ids := make([]ksuid.ID, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return auo.RemoveBookIDs(ids...)
}

// Where appends a list predicates to the AuthorUpdate builder.
func (auo *AuthorUpdateOne) Where(ps ...predicate.Author) *AuthorUpdateOne {
	auo.mutation.Where(ps...)
	return auo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (auo *AuthorUpdateOne) Select(field string, fields ...string) *AuthorUpdateOne {
	auo.fields = append([]string{field}, fields...)
	return auo
}

// Save executes the query and returns the updated Author entity.
func (auo *AuthorUpdateOne) Save(ctx context.Context) (*Author, error) {
	return withHooks(ctx, auo.sqlSave, auo.mutation, auo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (auo *AuthorUpdateOne) SaveX(ctx context.Context) *Author {
	node, err := auo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (auo *AuthorUpdateOne) Exec(ctx context.Context) error {
	_, err := auo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auo *AuthorUpdateOne) ExecX(ctx context.Context) {
	if err := auo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (auo *AuthorUpdateOne) check() error {
	if v, ok := auo.mutation.Name(); ok {
		if err := author.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Author.name": %w`, err)}
		}
	}
	return nil
}

func (auo *AuthorUpdateOne) sqlSave(ctx context.Context) (_node *Author, err error) {
	if err := auo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(author.Table, author.Columns, sqlgraph.NewFieldSpec(author.FieldID, field.TypeString))
	id, ok := auo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Author.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := auo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, author.FieldID)
		for _, f := range fields {
			if !author.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != author.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := auo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := auo.mutation.CalibreID(); ok {
		_spec.SetField(author.FieldCalibreID, field.TypeInt64, value)
	}
	if value, ok := auo.mutation.AddedCalibreID(); ok {
		_spec.AddField(author.FieldCalibreID, field.TypeInt64, value)
	}
	if value, ok := auo.mutation.Name(); ok {
		_spec.SetField(author.FieldName, field.TypeString, value)
	}
	if value, ok := auo.mutation.Sort(); ok {
		_spec.SetField(author.FieldSort, field.TypeString, value)
	}
	if value, ok := auo.mutation.Link(); ok {
		_spec.SetField(author.FieldLink, field.TypeString, value)
	}
	if auo.mutation.LinkCleared() {
		_spec.ClearField(author.FieldLink, field.TypeString)
	}
	if auo.mutation.BooksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   author.BooksTable,
			Columns: author.BooksPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.RemovedBooksIDs(); len(nodes) > 0 && !auo.mutation.BooksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   author.BooksTable,
			Columns: author.BooksPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.BooksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   author.BooksTable,
			Columns: author.BooksPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Author{config: auo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, auo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{author.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	auo.mutation.done = true
	return _node, nil
}
