// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

func (a *Author) Books(ctx context.Context) (result []*Book, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = a.NamedBooks(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = a.Edges.BooksOrErr()
	}
	if IsNotLoaded(err) {
		result, err = a.QueryBooks().All(ctx)
	}
	return result, err
}

func (b *Book) Authors(ctx context.Context) (result []*Author, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = b.NamedAuthors(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = b.Edges.AuthorsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = b.QueryAuthors().All(ctx)
	}
	return result, err
}
