// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"lybbrio/internal/ent/predicate"
	"lybbrio/internal/ent/seriesbook"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// SeriesBookDelete is the builder for deleting a SeriesBook entity.
type SeriesBookDelete struct {
	config
	hooks    []Hook
	mutation *SeriesBookMutation
}

// Where appends a list predicates to the SeriesBookDelete builder.
func (sbd *SeriesBookDelete) Where(ps ...predicate.SeriesBook) *SeriesBookDelete {
	sbd.mutation.Where(ps...)
	return sbd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sbd *SeriesBookDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, sbd.sqlExec, sbd.mutation, sbd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (sbd *SeriesBookDelete) ExecX(ctx context.Context) int {
	n, err := sbd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sbd *SeriesBookDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(seriesbook.Table, nil)
	if ps := sbd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, sbd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	sbd.mutation.done = true
	return affected, err
}

// SeriesBookDeleteOne is the builder for deleting a single SeriesBook entity.
type SeriesBookDeleteOne struct {
	sbd *SeriesBookDelete
}

// Where appends a list predicates to the SeriesBookDelete builder.
func (sbdo *SeriesBookDeleteOne) Where(ps ...predicate.SeriesBook) *SeriesBookDeleteOne {
	sbdo.sbd.mutation.Where(ps...)
	return sbdo
}

// Exec executes the deletion query.
func (sbdo *SeriesBookDeleteOne) Exec(ctx context.Context) error {
	n, err := sbdo.sbd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{seriesbook.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (sbdo *SeriesBookDeleteOne) ExecX(ctx context.Context) {
	if err := sbdo.Exec(ctx); err != nil {
		panic(err)
	}
}
