// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Author is the predicate function for author builders.
type Author func(*sql.Selector)

// Book is the predicate function for book builders.
type Book func(*sql.Selector)

// BookCover is the predicate function for bookcover builders.
type BookCover func(*sql.Selector)

// BookFile is the predicate function for bookfile builders.
type BookFile func(*sql.Selector)

// Identifier is the predicate function for identifier builders.
type Identifier func(*sql.Selector)

// Language is the predicate function for language builders.
type Language func(*sql.Selector)

// Publisher is the predicate function for publisher builders.
type Publisher func(*sql.Selector)

// Series is the predicate function for series builders.
type Series func(*sql.Selector)

// Shelf is the predicate function for shelf builders.
type Shelf func(*sql.Selector)

// Tag is the predicate function for tag builders.
type Tag func(*sql.Selector)

// Task is the predicate function for task builders.
type Task func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserPermissions is the predicate function for userpermissions builders.
type UserPermissions func(*sql.Selector)
