package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.43

import (
	"context"
	"fmt"
	"lybbrio/internal/ent"
	"lybbrio/internal/ent/user"
	"lybbrio/internal/viewer"
)

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*ent.User, error) {
	view := viewer.FromContext(ctx)
	if view == nil {
		return nil, fmt.Errorf("viewer-context is missing")
	}
	uid, ok := view.UserID()
	if !ok {
		return nil, fmt.Errorf("missing user information in viewer-context")
	}

	return r.client.User.Query().Where(user.ID(uid)).First(ctx)
}
